spring:
  cloud:
    stream:
      bindings:
        playerListenerQueue:
          destination: player2
        playerSenderQueue:
          destination: player1
        gameQueue:
          destination: game
        clientQueue:
          destination: client
server:
  port: 8090
